@php
    $sortColumn = $sortColumn ?? 'id';
    $sortDirection = $sortDirection ?? 'asc';
    $sortTh = 'Modules.Reliability.settings.master_data.partials.sort_th';
    $pairs = [
        ['id', 'id'],
        ['project_number', 'PROJECT #'],
        ['status', 'STATUS'],
        ['tail_number', 'TAIL NUMBER'],
        ['aircraft_type', 'AIRCRAFT TYPE'],
        ['scope', 'SCOPE'],
        ['open_date', 'OPEN DATE'],
        ['close_date', 'CLOSE DATE'],
        ['customer_number', 'CUSTOMER #'],
        ['customer_name', 'CUSTOMER NAME'],
        ['customer_po', 'CUSTOMER PO'],
        ['est_non_routine', 'EST.NON-ROUTINE'],
        ['target_days', 'TARGET DAYS'],
        ['arrival_date', 'ARRIVAL DATE'],
        ['induction_date', 'INDUCTION DATE'],
        ['inspection_date', 'INSPECTION DATE'],
        ['delivery_date', 'DELIVERY DATE'],
        ['rev_delivery_date', 'REV.DELIVERY DATE'],
        ['latest_delivery_date', 'LATEST DELIVERY DATE'],
        ['actual_arrival_date', 'ACTUAL ARRIVAL DATE'],
        ['actual_induction_date', 'ACTUAL INDUCTION DATE'],
        ['actual_inspection_date', 'ACTUAL INSPECTION DATE'],
        ['actual_delivery_date', 'ACTUAL DELIVERY DATE'],
        ['project_type', 'PROJECT TYPE'],
        ['applicable_standard', 'APPLICABLE STANDARD'],
        ['resources', 'RESOURCES'],
        ['bay', 'BAY'],
        ['planned_span', 'PLANNED SPAN'],
        ['day_of_check', 'DAY OF CHECK'],
        ['aircraft_tsn', 'AIRCRAFT TSN'],
        ['aircraft_csn', 'AIRCRAFT CSN'],
        ['engine_type', 'ENGINE TYPE'],
        ['quoted_mhrs', 'QUOTED MHRS'],
        ['oa_mhrs', 'O&A MHRS'],
        ['add_works_mhrs', 'ADD WORKS MHRS'],
        ['cwr_mhrs', 'CWR MHRS'],
        ['aircraft_series', 'AIRCRAFT SERIES'],
        ['station', 'STATION'],
        ['open_requisitions', 'OPEN REQUISITIONS'],
        ['open_order_lines', 'OPEN ORDER LINES'],
        ['awaiting_to_return_store', 'AWAITING TO RETURN STORE'],
        ['uninvoice_order_lines', 'UNINVOICE ORDER LINES'],
        ['open_work_cards', 'OPEN WORK CARDS'],
        ['open_work_orders', 'OPEN WORK ORDERS'],
        ['eng_mhrs', "ENG'G MHRS"],
        ['total_mhrs', 'TOTAL MHRS'],
        ['engine_1_serial', 'ENGINE 1 SERIAL'],
        ['engine_2_serial', 'ENGINE 2 SERIAL'],
        ['engine_3_serial', 'ENGINE 3 SERIAL'],
        ['engine_4_serial', 'ENGINE 4 SERIAL'],
        ['engine_1_tsn', 'ENGINE 1 TSN'],
        ['engine_1_csn', 'ENGINE 1 CSN'],
        ['engine_2_tsn', 'ENGINE 2 TSN'],
        ['engine_2_csn', 'ENGINE 2 CSN'],
        ['engine_3_tsn', 'ENGINE 3 TSN'],
        ['engine_3_csn', 'ENGINE 3 CSN'],
        ['engine_4_tsn', 'ENGINE 4 TSN'],
        ['engine_4_csn', 'ENGINE 4 CSN'],
        ['apu_pn', 'APU PN'],
        ['apu_serial', 'APU SERIAL'],
        ['apu_tsn', 'APU TSN'],
        ['apu_csn', 'APU CSN'],
        ['spares_order_cut_off', 'SPARES ORDER CUT OFF'],
        ['spares_delivery_cut_off', 'SPARES DELIVERY CUT OFF'],
        ['mhrs_cap', 'MHRS CAP'],
        ['created_at', 'created_at'],
        ['updated_at', 'updated_at'],
    ];
@endphp
@foreach ($pairs as [$col, $label])
    @include($sortTh, ['column' => $col, 'label' => $label, 'sortColumn' => $sortColumn, 'sortDirection' => $sortDirection])
@endforeach
