@php
    $sortColumn = $sortColumn ?? 'id';
    $sortDirection = $sortDirection ?? 'asc';
    $sortTh = 'Modules.Reliability.settings.master_data.partials.sort_th';
    $pairs = [
        ['id', 'id'],
        ['serial_number', 'SERIAL #'],
        ['tail_number', 'TAIL #'],
        ['aircraft_type', 'AIRCRAFT TYPE'],
        ['visit', 'VISIT'],
        ['customer_number', 'CUSTOMER #'],
        ['owner_number', 'OWNER #'],
        ['engine_type', 'ENGINE TYPE'],
        ['apu_type', 'APU TYPE'],
        ['group_code', 'GROUP CODE'],
        ['delivery_date', 'DELIVERY DATE'],
        ['redelivery_date', 'REDELIVERY DATE'],
        ['etops', 'ETOPS'],
        ['amm_group', 'AMM GROUP'],
        ['customer_name', 'CUSTOMER NAME'],
        ['owner_name', 'OWNER NAME'],
        ['app_std', 'APP. STD'],
        ['line_no', 'LINE NO'],
        ['variable_no', 'VARIABLE NO'],
        ['effectivity', 'EFFECTIVITY'],
        ['selcal', 'SELCAL'],
        ['lease_date', 'LEASE DATE'],
        ['manufactured', 'MANUFACTURED'],
        ['ins_date', 'INS. DATE'],
        ['pas_cap', 'PAS.CAP.'],
        ['seat_mat', 'SEAT MAT.'],
        ['max_taxi', 'MAX.TAXI'],
        ['max_to', 'MAX.TO.'],
        ['max_land', 'MAX.LAND'],
        ['maximum_zero_fuel_weight', 'MAXIMUM ZERO FUEL WEIGHT'],
        ['max_pay', 'MAX.PAY.'],
        ['dry_ope', 'DRY OPE.'],
        ['fuel', 'FUEL'],
        ['fuel_burn_ratio', 'FUEL BURN RATIO'],
        ['fwd_cargo', 'FWD CARGO'],
        ['aft_cargo', 'AFT CARGO'],
        ['fwd_area', 'FWD AREA'],
        ['aft_area', 'AFT AREA'],
        ['side_noise', 'SIDE NOISE'],
        ['app_noise', 'APP.NOISE'],
        ['start_noise', 'START NOISE'],
        ['eng_rate', 'ENG.RATE'],
        ['mod', 'MOD'],
        ['color', 'COLOR'],
        ['flight_number', 'FLIGHT NUMBER'],
        ['scheduled_from', 'SCHEDULED FROM'],
        ['scheduled_to', 'SCHEDULED TO'],
        ['scheduled_off_block', 'SCHEDULED OFF BLOCK'],
        ['scheduled_on_block', 'SCHEDULED ON BLOCK'],
        ['actual_from', 'ACTUAL FROM'],
        ['actual_to', 'ACTUAL TO'],
        ['actual_off_block', 'ACTUAL OFF BLOCK'],
        ['actual_on_block', 'ACTUAL ON BLOCK'],
        ['route_dev_dist', 'ROUTE DEV. DIST.'],
        ['route_dev_time', 'ROUTE DEV. TIME'],
        ['wng', 'WNG.'],
        ['archive', 'ARCHIVE'],
        ['active', 'ACTIVE'],
        ['created_at', 'created_at'],
        ['updated_at', 'updated_at'],
    ];
@endphp
@foreach ($pairs as [$col, $label])
    @include($sortTh, ['column' => $col, 'label' => $label, 'sortColumn' => $sortColumn, 'sortDirection' => $sortDirection])
@endforeach
