@php
    $sortColumn = $sortColumn ?? 'id';
    $sortDirection = $sortDirection ?? 'asc';
    $sortTh = 'Modules.Reliability.settings.master_data.partials.sort_th';
    $pairs = [
        ['id', 'id'],
        ['project', 'PROJECT'],
        ['project_type', 'PROJECT TYPE'],
        ['aircraft_type', 'AIRCRAFT TYPE'],
        ['tail_number', 'TAIL NUMBER'],
        ['bay', 'BAY'],
        ['wo_station', 'WO STATION'],
        ['work_order', 'WORK ORDER'],
        ['zone', 'ZONE'],
        ['item', 'ITEM'],
        ['quality_code', 'QUALITY CODE'],
        ['zones', 'ZONES'],
        ['status', 'STATUS'],
        ['wip_status', 'WIP STATUS'],
        ['reason', 'REASON'],
        ['src_order', 'SRC. ORDER'],
        ['src_zone', 'SRC. ZONE'],
        ['src_item', 'SRC. ITEM'],
        ['src_cust_card', 'SRC. CUST. CARD'],
        ['src_open_dt', 'SRC. OPEN DT.'],
        ['description', 'DESCRIPTION'],
        ['corrective_action', 'CORRECTIVE ACTION'],
        ['open_date', 'OPEN DATE'],
        ['close_date', 'CLOSE DATE'],
        ['planned_start', 'PLANNED START'],
        ['planned_finish_date', 'PLANNED FINISH DATE'],
        ['card_start_date', 'CARD START DATE'],
        ['card_finish_date', 'CARD FINISH DATE'],
        ['ms_start_day', 'MS START DAY'],
        ['ms_finish_day', 'MS FINISH DAY'],
        ['ms_start_date', 'MS START DATE'],
        ['ms_finish_date', 'MS FINISH DATE'],
        ['ms_description', 'MS DESCIPTION'],
        ['prim_skill', 'PRIM. SKILL'],
        ['skill_codes', 'SKILL CODES'],
        ['dot', 'DOT'],
        ['ata', 'ATA'],
        ['cust_card', 'CUST. CARD'],
        ['task_code', 'TASK CODE'],
        ['order_type', 'ORDER TYPE'],
        ['contract', 'CONTRACT'],
        ['contract_description', 'CONTRACT DESCRIPTION'],
        ['mpd_nrc_mhrs', 'MPD/NRC MHRS'],
        ['appr_time', 'APPR. TIME'],
        ['bill_time', 'BILL. TIME'],
        ['rem_est', 'REM. EST.'],
        ['rem_appr', 'REM. APPR.'],
        ['appl_time', 'APPL. TIME'],
        ['avg_time', 'AVG. TIME'],
        ['act_time', 'ACT. TIME'],
        ['app_user', 'APP.USER'],
        ['aircraft_location', 'AIRCRAFT LOCATION'],
        ['milestone', 'MILESTONE'],
        ['independent_inspector_number', 'INDEPENDENT INSPECTOR NUMBER'],
        ['inspector', 'INSPECTOR'],
        ['inspector_name', 'INSPECTOR NAME'],
        ['created_by', 'CREATED BY'],
        ['created_by_name', 'CREATED BY NAME'],
        ['performed_by_employee_number', 'PERFORMED BY EMPLOYEE#'],
        ['performed_date', 'PERFORMED DATE'],
        ['wo_dept', 'W/O DEPT'],
        ['work_order_department_name', 'WORK ORDER DEPARTMENT NAME'],
        ['shop', 'SHOP'],
        ['shop_description', 'SHOP DESCRIPTION'],
        ['department', 'DEPARTMENT'],
        ['department_name', 'DEPARTMENT NAME'],
        ['applicable_standard', 'APPLICABLE STANDARD'],
        ['form_applicable_standard', 'FORM APPLICABLE STANDARD'],
        ['form_number', 'FORM NUMBER'],
        ['panel_codes', 'PANEL CODES'],
        ['component_number', 'COMPONENT NUMBER'],
        ['comp_qty', 'COMP. QTY'],
        ['serial_number', 'SERIAL NUMBER'],
        ['services', 'SERVICES'],
        ['print_count', 'PRINT COUNT'],
        ['check_status', 'CHECK STATUS'],
        ['check_by_employee_number', 'CHECK BY EMPLOYEE NUMBER'],
        ['check_by_employee_name', 'CHECK BY EMPLOYEE NAME'],
        ['check_date', 'CHECK DATE'],
        ['documents', 'DOCUMENTS'],
        ['manufacturer', 'MANUFACTURER'],
        ['estimator_comment', 'ESTIMATOR COMMENT'],
        ['representative_comment', 'REPRESENTATIVE COMMENT'],
        ['controller_comment', 'CONTROLLER COMMENT'],
        ['findings', 'FINDINGS'],
        ['customer_number', 'CUSTOMER#'],
        ['customer', 'CUSTOMER'],
        ['inspection_date', 'INSPECTION DATE'],
        ['part_description', 'PART DESCRIPTION'],
        ['auth_type', 'AUTH. TYPE'],
        ['condition_code', 'CONDITION CODE'],
        ['condition', 'CONDITION'],
        ['etops', 'ETOPS'],
        ['critical', 'CRITICAL'],
        ['ils', 'ILS'],
        ['rii', 'RII'],
        ['cdccl', 'CDCCL'],
        ['leak_c', 'LEAK C.'],
        ['open', 'OPEN'],
        ['close', 'CLOSE'],
        ['lube', 'LUBE'],
        ['sdr', 'SDR'],
        ['structural', 'STRUCTURAL'],
        ['engine_run', 'ENGINE RUN'],
        ['on_floor', 'ON FLOOR'],
        ['major', 'MAJOR'],
        ['alter', 'ALTER'],
        ['cpcp', 'CPCP'],
        ['logon', 'LOGON'],
        ['only_assigned', 'ONLY ASSIGNED'],
        ['aircraft', 'AIRCRAFT'],
        ['gqar', 'GQAR'],
        ['billable', 'BILLABLE'],
        ['lock', 'LOCK'],
        ['open_steps_number', 'OPEN STEPS#'],
        ['total_steps_number', 'TOTAL STEPS#'],
        ['maint_start_date', 'MAINT.START DATE'],
        ['child_card_count', 'CHILD CARD COUNT'],
        ['group_code', 'GROUP CODE'],
        ['pocket_number', 'POCKET#'],
        ['pin_pocket', 'PIN POCKET'],
        ['handover', 'HANDOVER'],
        ['incoming_defect', 'INCOMING DEFECT'],
        ['mandatory', 'MANDATORY'],
        ['est_mhrs', 'EST. MHRS'],
        ['dmi_due_date', 'DMI DUE DATE'],
        ['dmi_reference', 'DMI REFERENCE'],
        ['cmm_reference', 'CMM REFERENCE'],
        ['ext_no', 'EXT NO'],
        ['ac_msn', 'AC MSN'],
        ['serv_hrs', 'SERV. HRS.'],
        ['barcode_print_count', 'BARCODE PRINT COUNT'],
        ['completed_time_utc', 'COMPLETED TIME (UTC)'],
        ['created_at', 'created_at'],
        ['updated_at', 'updated_at'],
    ];
@endphp
@foreach ($pairs as [$col, $label])
    @include($sortTh, ['column' => $col, 'label' => $label, 'sortColumn' => $sortColumn, 'sortDirection' => $sortDirection])
@endforeach
